// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	"bk_monitor_notify/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/api/notify/larkBot",
				Handler: larkBotHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/api/notify/dingTalkBot",
				Handler: dingTalkBotHandler(serverCtx),
			},
		},
	)
}
